FROM gammaforceio/infra:latest

# Figure out how to make this a second FROM so we don't reinstall these modules
# every time we run a test
RUN pip3 install \
      pytest \
      pytest-describe \
      coverage

COPY tests /opt/infra/tests

WORKDIR "/opt/infra"

ENTRYPOINT ["/opt/infra/tests/run_with_coverage.sh"]
